### ISSUE TITLE
Tests requiring AssertJ Swing as a Maven dependency encounter a NoClassDefFoundError under Pit

### ISSUE THREAD

**Issue by ben-clegg** [hcoles/pitest#881]
I have some JUnit tests for my Swing GUI using AssertJ-Swing, which work fine under other Maven `test` goals, but they crash out when running Pit. In addition, my other (non-AssertJ) tests work fine with Pit.
This issue occurs for both OpenJDK 11 and OpenJDK 8.

The exact issue I am facing is that a `java.lang.NoClassDefFoundError` is thrown when running any `AssertJSwingJUnitTestCase`, when it tries to access `org.assertj.swing.core.BasicRobot`.

I have all of my testing dependencies included in my `pom.xml`, under the `test` scope.
I have also tried explicitly including AssertJ JAR as additional classpath elements.
I've uploaded a gist of my `pom.xml` here: https://gist.github.com/ben-clegg/c73660b2cdbc82d01dbdcd038fd23adb

Since this works fine with other Maven goals, I believe this is an issue with Pit. 
Does Pit have similar issues with other Maven dependencies, or is this unique to AssertJ?
Can you suggest any workarounds?

Thanks

**Comment by StefanPenndorf** [comment]
Hi @ben-clegg 

Could you provide the full stack trace of the NoClassDefFoundError?

Pitest uses `-Djava.awt.headless=true` to prevent stealing focus on Mac (see #581). This might interfere with GUI-testing.

**Comment by ben-clegg** [comment]
Hi Stefan,

Thanks for the reply. Here are the logs with the headless setting enabled and disabled, the issue seems to occur with or without this setting. In case it helps, I'm using Linux.

Default : https://gist.github.com/ben-clegg/975ffbd09e0850e2b0208884e308d7ab
No Headless : https://gist.github.com/ben-clegg/3a1875904115aabfde2f60be15e41fd4

Thanks

**Comment by StefanPenndorf** [comment]
As your stacktraces tell HeadlessGraphicsEnvironment will be used which fails with HeadlessException in either gist. You cannot disable headless for test minions due to #581 .

The change merged in #601 adds `-Djava.awt.headless=true` to every mutation minion created. There is only the option to add further settings but not to remove the default.

So far so good. The problems seems the new default introduced in #601 . 

@hcoles 
What do you think would be the best solution: Remove the default and warn Mac users that they should add `-Djava.awt.headless=true` themselves or should one introduce another configuration option that lets one turn headless on/off ?

**Comment by jzy3d** [comment]
To my opinion, it would be nice to get a suggestion for the CLI when a headless exception is thrown. I spent little time to figure out where the problem came from (I dropped the solution [here](https://github.com/hcoles/pitest/issues/1033) for others).

**Comment by ron190** [comment]
Hello, the same occurs for [this test suite](https://github.com/ron190/jsql-injection/blob/master/view/src/test/java/com/test/assertj/AppUiTest.java), the suite was throwing `HeadlessException` with pitest, now it starts when adding `-Dfeatures="-macos_focus"`, but on windows.

By default assertj fails on [java.awt.GraphicsEnvironment.checkHeadless()](https://github.com/elastic/openjdkMirror/blob/master/jdk/src/share/classes/java/awt/GraphicsEnvironment.java#L189) because of `-Djava.awt.headless=true` that pitest adds, so the var you propose @hcoles helps to make it start.

Though, here are additional feedback about non-headless execution. Pitest looks applicable to GUI testing, but possibly some specific practice is required for a smooth run :
- The [suite](https://github.com/ron190/jsql-injection/blob/master/view/src/test/java/com/test/assertj/AppUiTest.java) have 20 methods and takes 35 seconds on local without pitest. At startup with pitest, logs are showing :
```sh
Slowest test ([engine:junit-jupiter]/[shouldDnDTabs()]) took 35s
Largest test ([engine:junit-jupiter]/[shouldFindFile()]) covered 4852 blocks
PIT >> INFO : Created 336 mutation test units
```
- But with pitest it was still running after 2 hours 30 minutes, before I interrupt the execution
- As no indicator was showing any progress during the 2h30 run, I was not sure that execution was fine or was progressing. I didn't know how many tests or how many mutations pitest had already executed
- During the process, suite methods were properly running parts of the GUI buisness for 10s, showing that pitest was correctly running mutations
- Then a period of 20s of no visible activity was occuring
- Then the entire suite of 20 methods was running again for 35s without failure
- Then same process was repeating over and over : 10s methods mutation, then 20s inactive period, then 35s for full suite

During GUI testing, the inactive periods and the green full suite executions are looking strange, like a reset. I don't get this behavior on [non-GUI testing](https://github.com/ron190/jsql-injection/tree/master/model/src/test/groovy) with pitest.
